[package]
name = "powervoice-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
default-run = "powervoice-cli"

[[bin]]
name = "powervoice-cli"
path = "src/main.rs"

[dependencies]
clap.workspace = true
vox-testkit = { path = "../testkit" }
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true

[lints]
workspace = true
