//! Live output analyzer DTOs (T-208, SPEC-007 §2.9/§4.8–§4.9): the `AnalyzerResponseDto` enum
//! for `analyzer_subscribe`/`analyzer_set_response`, and the Rust-generated `VXSA` fixture for
//! the TS decoder test (ADR-003 §4, ADR-003 Amendment 4).

use serde::{Deserialize, Serialize};
use ts_rs::TS;
use vox_engine::AnalyzerResponse;

/// Analyzer averaging response (Fast/Medium/Slow, SPEC-007 §2.9), exponential averaging in the
/// power domain with τ = 50 / 150 / 500 ms.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "snake_case")]
#[ts(export, export_to = "bindings.ts", rename_all = "snake_case")]
pub enum AnalyzerResponseDto {
    Fast,
    Medium,
    Slow,
}

impl From<AnalyzerResponseDto> for AnalyzerResponse {
    fn from(d: AnalyzerResponseDto) -> Self {
        match d {
            AnalyzerResponseDto::Fast => AnalyzerResponse::Fast,
            AnalyzerResponseDto::Medium => AnalyzerResponse::Medium,
            AnalyzerResponseDto::Slow => AnalyzerResponse::Slow,
        }
    }
}

impl From<AnalyzerResponse> for AnalyzerResponseDto {
    fn from(r: AnalyzerResponse) -> Self {
        match r {
            AnalyzerResponse::Fast => AnalyzerResponseDto::Fast,
            AnalyzerResponse::Medium => AnalyzerResponseDto::Medium,
            AnalyzerResponse::Slow => AnalyzerResponseDto::Slow,
        }
    }
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use vox_engine::{AnalyzerFrame, AnalyzerResponse};

    /// Writes the golden `VXSA` frame for the TS decoder test (SPEC-007 §4.9: generated by the
    /// `export_bindings` run of `just gen-types`, checked by `just check-types`).
    #[test]
    fn export_bindings_vxsa_fixture() {
        let f = AnalyzerFrame {
            seq: 11,
            reset: true,
            dropped: false,
            silent: false,
            frame_time_ns: 555_555_555_000,
            sample_rate_hz: 48_000,
            fft_size: 8192,
            band_count: 4,
            response: AnalyzerResponse::Medium,
            levels_db: vec![-120.0, -20.375, 0.0, f32::NEG_INFINITY],
        };
        let hex: String = f.encode().iter().map(|b| format!("{b:02x}")).collect();
        let ts = format!(
            "// Generated by the `export_bindings_vxsa_fixture` test (src-tauri, `just gen-types`). Do not edit.\n\
             \n\
             /** A `VXSA` frame encoded by Rust (`AnalyzerFrame::encode`) for the TS decoder contract test. */\n\
             export const VXSA_FIXTURE_HEX =\n  \"{hex}\";\n\
             \n\
             /** The field values encoded in `VXSA_FIXTURE_HEX`. */\n\
             export const VXSA_FIXTURE_FIELDS = {{\n  \
             seq: 11,\n  reset: true,\n  dropped: false,\n  silent: false,\n  \
             frameTimeNs: 555555555000,\n  sampleRateHz: 48000,\n  fftSize: 8192,\n  \
             f0Hz: 20,\n  bandsPerOctave: 24,\n  bandCount: 4,\n  response: 1,\n  \
             levelsDb: [-120, -20.375, 0, -Infinity],\n}} as const;\n",
        );
        let dir = std::env::var_os("TS_RS_EXPORT_DIR")
            .map(PathBuf::from)
            .unwrap_or_else(|| PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("bindings"));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("vxsa_fixture.ts"), ts).unwrap();
    }
}
