//! T-204 spectrogram DTOs (ADR-003 §2 `spectro_request`). The tiles themselves are binary `VXST`
//! frames on the view's channel (`vox_engine::spectro`), never JSON.

use serde::{Deserialize, Serialize};
use ts_rs::TS;
use vox_engine::spectro::SpectroRequest;

/// One `spectro_request`: FFT size, hop (from the zoom, SPEC-007 §4.3), window (0 = Hann) and up
/// to 64 tile indices, visible tiles first.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[ts(export, export_to = "bindings.ts")]
pub struct SpectroRequestDto {
    pub request_id: u32,
    pub audio_rev: u64,
    pub fft_size: u32,
    pub hop: u32,
    pub window: u32,
    pub tiles: Vec<u32>,
}

impl From<SpectroRequestDto> for SpectroRequest {
    fn from(dto: SpectroRequestDto) -> Self {
        SpectroRequest {
            request_id: dto.request_id,
            audio_rev: dto.audio_rev,
            fft_size: dto.fft_size,
            hop: dto.hop,
            window: dto.window,
            tiles: dto.tiles,
        }
    }
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use vox_engine::spectro::{VxstHeader, WINDOW_HANN, encode_vxst, vxst_flags};

    /// Payload rule of the fixture frames: code `i` = `(i·37 + 11) mod 256` (the TS test
    /// recomputes it).
    fn payload(len: usize) -> Vec<u8> {
        (0..len).map(|i| ((i * 37 + 11) % 256) as u8).collect()
    }

    /// Writes golden `VXST` frames (one `PREVIEW`, one `LAST`) for the TS decoder contract test
    /// (SPEC-007 AC-6, ADR-003 §4: generated by `just gen-types`, checked by `just check-types`).
    #[test]
    fn export_bindings_vxst_fixture() {
        let preview = VxstHeader {
            request_id: 7,
            flags: vxst_flags::PREVIEW,
            audio_rev: 42,
            first_frame_center_sample: 3 * 256 * 8192,
            hop_samples: 8192,
            fft_size: 256,
            frames: 2,
            bins: 129,
            q_floor_db: -150.0,
            q_ceil_db: 6.0,
            tile_index: 3,
            window: WINDOW_HANN,
        };
        let last = VxstHeader {
            flags: vxst_flags::LAST,
            first_frame_center_sample: 4 * 256 * 8192,
            frames: 1,
            tile_index: 4,
            ..preview
        };
        let entry = |h: &VxstHeader| {
            let bytes = encode_vxst(h, &payload((h.frames * h.bins) as usize));
            let hex: String = bytes.iter().map(|b| format!("{b:02x}")).collect();
            format!(
                "  {{\n    hex: \"{hex}\",\n    fields: {{\n      requestId: {},\n      flags: {},\n      \
                 last: {},\n      preview: {},\n      audioRev: {},\n      firstFrameCenterSample: {},\n      \
                 hopSamples: {},\n      fftSize: {},\n      frames: {},\n      bins: {},\n      qFloorDb: -150,\n      \
                 qCeilDb: 6,\n      tileIndex: {},\n      window: {},\n    }},\n  }},\n",
                h.request_id,
                h.flags,
                h.flags & vxst_flags::LAST != 0,
                h.flags & vxst_flags::PREVIEW != 0,
                h.audio_rev,
                h.first_frame_center_sample,
                h.hop_samples,
                h.fft_size,
                h.frames,
                h.bins,
                h.tile_index,
                h.window,
            )
        };
        let ts = format!(
            "// Generated by the `export_bindings_vxst_fixture` test (src-tauri, `just gen-types`). Do not edit.\n\
             \n\
             /**\n * `VXST` frames encoded by Rust (`vox_engine::spectro::encode_vxst`) for the TS decoder contract\n \
             * test. Payload code `i` is `(i * 37 + 11) % 256`.\n */\n\
             export const VXST_FIXTURES = [\n{}{}] as const;\n",
            entry(&preview),
            entry(&last),
        );
        let dir = std::env::var_os("TS_RS_EXPORT_DIR")
            .map(PathBuf::from)
            .unwrap_or_else(|| PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("bindings"));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("vxst_fixture.ts"), ts).unwrap();
    }
}
