/**
 * H-59: the Rust↔TS layout contract for `VXPK` (ADR-003 §2, §4). `vxpk.test.ts` builds its bytes
 * in TS from the spec table, so it can only prove the decoder is self-consistent; this one
 * decodes bytes `vox_project::encode_vxpk` actually produced (`ui/src/lib/ipc/vxpk_fixture.ts`,
 * regenerated by `just gen-types`), which is what catches a drift on either side — the pattern
 * VXST/VXTM/VXMT/VXSA already had and VXPK did not.
 */
import { describe, expect, it } from "vitest";
import { VXPK_FIXTURES } from "../ipc/vxpk_fixture";
import { decodeVxpk } from "./vxpk";

function bytes(hex: string): ArrayBuffer {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = Number.parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return out.buffer;
}

/** The fixture's payload rule, recomputed here: bucket `i` = `(-(1 + i / 8), 1 + i / 8)`. */
function expectedBucket(i: number): [number, number] {
  const d = 1 + i / 8;
  return [-d, d];
}

describe("VXPK golden frames from Rust", () => {
  it.each(VXPK_FIXTURES.map((f, i) => [i, f] as const))(
    "decodes fixture %i field for field",
    (_i, fixture) => {
      const frame = decodeVxpk(bytes(fixture.hex));
      expect(frame).not.toBeNull();
      expect(frame).toMatchObject(fixture.fields);
      expect(frame?.buckets).toHaveLength(fixture.fields.count);
    },
  );

  it("reads bucket pairs, and RAW frames as single samples repeated as (v, v)", () => {
    const [bucketFrame, rawFrame] = VXPK_FIXTURES;
    const buckets = decodeVxpk(bytes(bucketFrame.hex))?.buckets ?? [];
    const raws = decodeVxpk(bytes(rawFrame.hex))?.buckets ?? [];
    for (let i = 0; i < buckets.length; i++) {
      const [min, max] = expectedBucket(i);
      expect(buckets[i]).toEqual([min, max]);
      // RAW keeps only the first value of each pair (spp = 1, so min === max per sample).
      expect(raws[i]).toEqual([min, min]);
    }
  });

  it("carries a start_sample above 2^32, so the u64 split is right in both languages", () => {
    const frame = decodeVxpk(bytes(VXPK_FIXTURES[0].hex));
    expect(frame?.startSample).toBe(2 ** 32);
  });
});
