[package]
name = "vox-rack"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
vox-module-api = { path = "../module-api" }
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
rtrb.workspace = true

[dev-dependencies]
vox-module-api = { path = "../module-api", features = ["test-util"] }
vox-modules = { path = "../modules" }
vox-testkit = { path = "../testkit" }

[lints]
workspace = true
