// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Basic app identity shown by the UI at startup. Returned by the `app_info` command.
 */
export type AppInfo = { name: string, version: string, };

export type BitDepth = "16" | "24" | "32f";

export type CommandName = "app_info" | "settings_get" | "settings_set" | "devices_list" | "devices_select" | "transport_get" | "transport_play" | "transport_pause" | "transport_stop" | "transport_play_from_start" | "transport_return_to_start" | "transport_seek" | "telemetry_subscribe" | "clock_now_ns" | "document_open" | "document_save" | "document_save_as" | "peaks_get";

export type DefaultFormatDto = { sample_rate_hz: number, bit_depth: BitDepth, };

/**
 * One device of the selected host.
 */
export type DeviceDto = { 
/**
 * Unique name (the key saved in the prefs).
 */
name: string, 
/**
 * Display name.
 */
base_name: string, input: boolean, output: boolean, 
/**
 * A "follow the system default" pseudo-device.
 */
system_default: boolean, 
/**
 * Its capture side monitors an output (hidden from the input list).
 */
input_is_monitor: boolean, 
/**
 * SPEC-001 §2.1 common rates the output supports (empty while unknown).
 */
output_rates_hz: Array<number>, 
/**
 * SPEC-001 §2.1 common buffer sizes within the output's range ("Auto" is implicit).
 */
output_buffer_sizes: Array<number>, };

/**
 * Persisted device selection — "saved intent", not the applied value: SPEC-001 §2.5 requires
 * that a value which triggered a runtime fallback (unsupported sample rate, out-of-range buffer
 * size) is still saved as the user's *intent*, so PowerVoice retries it next time the device's
 * capabilities might have changed. This DTO therefore never carries a "what was actually
 * applied" field — that belongs to runtime state/telemetry (a later ticket), not settings.
 */
export type DevicePrefsDto = { 
/**
 * Audio host/backend id (SPEC-001 §3: `alsa`|`pipewire`|`jack` on Linux, `wasapi` on
 * Windows, `coreaudio` on macOS). Kept as a plain string rather than a closed enum: only
 * the engine (T-102) can enumerate which hosts actually exist on this machine.
 */
host: string, 
/**
 * `None` = "None" (SPEC-001 §3 factory default; disarms recording/monitoring input).
 * Otherwise the device's host-reported name — devices are keyed by `(host, name)`, not
 * index (SPEC-001 §2.2: cpal indices aren't stable across enumerations).
 */
input_device: string | null, 
/**
 * 1-based input channel index (SPEC-001 §3: `1..=N`, N = device max input channels).
 */
input_channel: number, 
/**
 * `None` = host default output device (SPEC-001 §3).
 */
output_device: string | null, 
/**
 * `None` = device default sample rate ("Auto" is not a documented option for rate in
 * SPEC-001 §3, but no saved preference yet behaves the same as "use the device default").
 */
sample_rate_hz: number | null, 
/**
 * `None` = "Auto" (device default; SPEC-001 §3 factory default).
 */
buffer_size_frames: number | null, };

/**
 * Output status dot (SPEC-001 §2.3).
 */
export type DeviceStatusDto = "not_selected" | "healthy" | "fallback" | "lost";

/**
 * The Audio Devices dialog's data (`devices_list`, `devices_select`, `devices_changed`).
 */
export type DevicesDto = { hosts: Array<string>, host: string | null, devices: Array<DeviceDto>, default_input: string | null, default_output: string | null, 
/**
 * The saved intent.
 */
prefs: DevicePrefsDto, 
/**
 * Applied output device, rate and buffer (`None` = Auto / not open).
 */
output_device: string | null, output_rate_hz: number | null, output_buffer_frames: number | null, output_status: DeviceStatusDto, };

/**
 * `document_changed` event payload, and the result of `document_open`/`document_save`/
 * `document_save_as`. `name: None` means no document is open.
 */
export type DocumentDto = { name: string | null, path: string | null, sample_rate_hz: number, len_samples: number, dirty: boolean, audio_rev: number, };

export type EventName = "notice" | "transport_state" | "devices_changed" | "document_changed";

/**
 * Error shape returned by every command (ADR-003). `key` is an i18n key, `params` fills its
 * placeholders (CLAUDE.md: every user-facing string goes through i18n — commands never return
 * pre-rendered text).
 */
export type IpcError = { code: IpcErrorCode, key: string, params: { [key in string]: string }, };

/**
 * Coarse error classification shared by every command (ADR-003). This ticket (T-104) fixes the
 * taxonomy shape and fills in the codes already named by an approved spec/ADR; a command-owning
 * ticket adds a new variant here only when its own spec names a distinct error condition, to
 * keep this a small, meaningful set rather than one variant per command.
 */
export type IpcErrorCode = "internal" | "invalid_argument" | "not_found" | "not_while_recording" | "device_not_found" | "device_lost" | "io" | "cancelled";

export type MonitorMode = "off" | "dry" | "through_rack";

/**
 * A user-facing notice (ADR-003 `notice` event). Two shapes, distinguished by `persistent`:
 * - a **toast** (`persistent: false`, `id: None`): transient, auto-dismisses in the UI (e.g.
 *   SPEC-001 §2.3's fallback/reconnect notices).
 * - a **banner** (`persistent: true`, `id: Some(..)`): stays until the user dismisses it or
 *   another `Notice` with the same `id` replaces/clears it (e.g. SPEC-001 §2.3's device-lost
 *   banner turning into a brief "reconnected" notice).
 *
 * `key`/`params` is an i18n message key plus its placeholder values (CLAUDE.md: every
 * user-facing string goes through i18n) — this event never carries pre-rendered text.
 */
export type Notice = { level: NoticeLevel, key: string, params: { [key in string]: string }, persistent: boolean, 
/**
 * Stable id for a banner that a later `Notice` can replace or clear. `None` for one-shot
 * toasts, which are never replaced (each is its own event).
 */
id: string | null, };

export type NoticeLevel = "info" | "warning" | "error";

/**
 * `peaks_get`'s request (ADR-003 §2's `PeaksRequest`). `audio_rev` is the revision the UI last
 * saw; the server always answers with the document's *current* `audio_rev` regardless (in its
 * `VXPK` response header) — staleness is the caller's problem to detect (ADR-003: "the UI drops
 * any response whose `audio_rev` is not current"), not something this command refuses.
 */
export type PeaksRequestDto = { request_id: number, audio_rev: number, spp: number, start_sample: number, count: number, };

/**
 * The whole settings file. `#[serde(default)]` at the container level means any field missing
 * from the on-disk JSON (an older/partial file) is filled from [`Settings::default`], and the
 * flattened `extra` map preserves any *unknown* field a future version wrote, so round-tripping
 * through this version never silently drops it (acceptance criterion: "unknown future fields
 * preserved").
 */
export type Settings = { version: number, device: DevicePrefsDto, default_format: DefaultFormatDto, monitor_mode: MonitorMode, 
/**
 * SPEC-003 §3: {30, 60} Hz, default 60 (measured free on WebKitGTK, ADR-009 §3).
 */
telemetry_rate_hz: number, memory_budget_mib: number, };

/**
 * Transport state (`transport_state` event, transport command results). While playing, the
 * moving playhead comes from `VXTM` telemetry; `playhead_samples` is then where the pass began.
 */
export type TransportStateDto = { playing: boolean, playhead_samples: number, play_start_samples: number, doc_len_samples: number, doc_rate_hz: number, 
/**
 * A document is loaded and an output device is open.
 */
can_play: boolean, };
