// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Basic app identity shown by the UI at startup. Returned by the `app_info` command.
 */
export type AppInfo = { name: string, version: string, };

export type BitDepth = "16" | "24" | "32f";

/**
 * S2-01: the clipboard's length/rate (`clipboard_changed` event); `null` fields mean it's empty
 * (SPEC-008 §4.3).
 */
export type ClipboardChangedDto = { len_samples: number | null, sample_rate_hz: number | null, };

export type CommandName = "app_info" | "settings_get" | "settings_set" | "devices_list" | "devices_select" | "transport_get" | "transport_play" | "transport_pause" | "transport_stop" | "transport_play_from_start" | "transport_return_to_start" | "transport_seek" | "telemetry_subscribe" | "clock_now_ns" | "rack_list_modules" | "rack_get" | "rack_add" | "rack_remove" | "rack_move" | "rack_bypass" | "rack_ab" | "rack_restart" | "param_set_normalized" | "param_set_text" | "record_get" | "record_arm" | "record_start" | "record_stop" | "record_set_monitor" | "record_peaks_get" | "document_open" | "document_save" | "document_save_as" | "peaks_get" | "edit_cut" | "edit_copy" | "edit_paste" | "edit_delete" | "edit_trim" | "edit_silence" | "edit_normalize_peak" | "history_undo" | "history_redo" | "markers_get" | "marker_add" | "marker_rename" | "marker_set_range" | "marker_delete" | "export_formats" | "export_start" | "export_cancel";

export type DefaultFormatDto = { sample_rate_hz: number, bit_depth: BitDepth, };

/**
 * One device of the selected host.
 */
export type DeviceDto = { 
/**
 * Unique name (the key saved in the prefs).
 */
name: string, 
/**
 * Display name.
 */
base_name: string, input: boolean, output: boolean, 
/**
 * Input channels (S1-04 channel dropdown; 0 while unknown).
 */
input_channels: number, 
/**
 * A "follow the system default" pseudo-device.
 */
system_default: boolean, 
/**
 * Its capture side monitors an output (hidden from the input list).
 */
input_is_monitor: boolean, 
/**
 * SPEC-001 §2.1 common rates the output supports (empty while unknown).
 */
output_rates_hz: Array<number>, 
/**
 * SPEC-001 §2.1 common buffer sizes within the output's range ("Auto" is implicit).
 */
output_buffer_sizes: Array<number>, };

/**
 * Persisted device selection — "saved intent", not the applied value: SPEC-001 §2.5 requires
 * that a value which triggered a runtime fallback (unsupported sample rate, out-of-range buffer
 * size) is still saved as the user's *intent*, so PowerVoice retries it next time the device's
 * capabilities might have changed. This DTO therefore never carries a "what was actually
 * applied" field — that belongs to runtime state/telemetry (a later ticket), not settings.
 */
export type DevicePrefsDto = { 
/**
 * Audio host/backend id (SPEC-001 §3: `alsa`|`pipewire`|`jack` on Linux, `wasapi` on
 * Windows, `coreaudio` on macOS). Kept as a plain string rather than a closed enum: only
 * the engine (T-102) can enumerate which hosts actually exist on this machine.
 */
host: string, 
/**
 * `None` = "None" (SPEC-001 §3 factory default; disarms recording/monitoring input).
 * Otherwise the device's host-reported name — devices are keyed by `(host, name)`, not
 * index (SPEC-001 §2.2: cpal indices aren't stable across enumerations).
 */
input_device: string | null, 
/**
 * 1-based input channel index (SPEC-001 §3: `1..=N`, N = device max input channels).
 */
input_channel: number, 
/**
 * `None` = host default output device (SPEC-001 §3).
 */
output_device: string | null, 
/**
 * `None` = device default sample rate ("Auto" is not a documented option for rate in
 * SPEC-001 §3, but no saved preference yet behaves the same as "use the device default").
 */
sample_rate_hz: number | null, 
/**
 * `None` = "Auto" (device default; SPEC-001 §3 factory default).
 */
buffer_size_frames: number | null, };

/**
 * Output status dot (SPEC-001 §2.3).
 */
export type DeviceStatusDto = "not_selected" | "healthy" | "fallback" | "lost";

/**
 * The Audio Devices dialog's data (`devices_list`, `devices_select`, `devices_changed`).
 */
export type DevicesDto = { hosts: Array<string>, host: string | null, devices: Array<DeviceDto>, default_input: string | null, default_output: string | null, 
/**
 * The saved intent.
 */
prefs: DevicePrefsDto, 
/**
 * Applied output device, rate and buffer (`None` = Auto / not open).
 */
output_device: string | null, output_rate_hz: number | null, output_buffer_frames: number | null, output_status: DeviceStatusDto, 
/**
 * The configured input device and its status dot (S1-04).
 */
input_device: string | null, input_status: DeviceStatusDto, };

/**
 * `document_changed` event payload, and the result of `document_open`/`document_save`/
 * `document_save_as`. `name: None` means no document is open.
 */
export type DocumentDto = { name: string | null, path: string | null, sample_rate_hz: number, len_samples: number, dirty: boolean, audio_rev: number, };

/**
 * S2-01: the result of a cut/copy/paste/delete/trim/silence command or an undo/redo (SPEC-008
 * §4.3's `EditResult`, minus `rev`/`base_rev` — revision-guarded commands are deferred).
 * `changed: false` only for Copy, a whole-document Trim, and undo/redo at the history's edge.
 */
export type EditResultDto = { changed: boolean, audio_rev: number, len_samples: number, 
/**
 * `[start, end)` document samples, or `null` (no selection).
 */
selection: [number, number] | null, playhead_samples: number, };

/**
 * S2-01: where `edit_paste` inserts or replaces (SPEC-008 §2.1). The UI resolves "no selection"
 * to `Cursor` itself (SPEC-008 §2.2: an empty selection counts as the cursor).
 */
export type EditTargetDto = { "kind": "cursor", at_samples: number, } | { "kind": "range", start_samples: number, end_samples: number, };

export type EventName = "notice" | "transport_state" | "devices_changed" | "rack_changed" | "param_changed" | "rack_latency" | "record_state" | "document_changed" | "history_state" | "clipboard_changed" | "job_progress";

/**
 * Export output format and its per-format settings. FLAC's `bits` rejects `"32f"` (FLAC has no
 * float sample format, SPEC-005 §2.11) with `error.export.flac_no_float`.
 */
export type ExportFormatDto = { "kind": "wav", bits: BitDepth, } | { "kind": "flac", bits: BitDepth, } | { "kind": "mp3", settings: Mp3SettingsDto, };

/**
 * `export_formats`' result: whether MP3 is available on this system (ADR-007 §4, D-013). WAV and
 * FLAC are always available.
 */
export type ExportFormatsDto = { mp3_available: boolean, };

/**
 * `[start_sample, end_sample)` of the export (a selection); omitted in the request = whole file.
 */
export type ExportRangeDto = { start_sample: number, end_sample: number, };

/**
 * `export_start`'s argument.
 */
export type ExportRequestDto = { path: string, format: ExportFormatDto, sample_rate_hz: number, range: ExportRangeDto | null, };

/**
 * `export_start`'s result: the export runs in the background, reporting `job_progress` events
 * tagged with this `job_id` (`export_cancel(job_id)` stops it).
 */
export type ExportStartedDto = { job_id: number, };

/**
 * S2-01: the Edit menu's Undo/Redo state (`history_state` event). Labels are i18n keys
 * (`history.cut`, …, CLAUDE.md), `null` when there's nothing to undo/redo.
 */
export type HistoryStateDto = { can_undo: boolean, can_redo: boolean, undo_label: string | null, redo_label: string | null, };

/**
 * Error shape returned by every command (ADR-003). `key` is an i18n key, `params` fills its
 * placeholders (CLAUDE.md: every user-facing string goes through i18n — commands never return
 * pre-rendered text).
 */
export type IpcError = { code: IpcErrorCode, key: string, params: { [key in string]: string }, };

/**
 * Coarse error classification shared by every command (ADR-003). This ticket (T-104) fixes the
 * taxonomy shape and fills in the codes already named by an approved spec/ADR; a command-owning
 * ticket adds a new variant here only when its own spec names a distinct error condition, to
 * keep this a small, meaningful set rather than one variant per command.
 */
export type IpcErrorCode = "internal" | "invalid_argument" | "not_found" | "not_while_recording" | "device_not_found" | "device_lost" | "io" | "cancelled";

/**
 * A long-running, cancellable job's kind (ADR-003 `job_progress`; S4-04 is the first job). New
 * job kinds add a variant here rather than a new event, so the frontend has one progress/cancel
 * pattern for every job.
 */
export type JobKind = "export";

/**
 * `job_progress` event payload (ADR-003; ≤ 10 Hz per job). `job_id` distinguishes overlapping or
 * stale jobs of the same `kind`; a failure's message goes out separately as a `notice` (the same
 * convention `error.*`/`notice.*` i18n keys use everywhere else), not inline here.
 */
export type JobProgressDto = { job_id: number, kind: JobKind, state: JobState, fraction: number, };

/**
 * `job_progress`'s lifecycle. `Running` fractions are monotonically non-decreasing in `[0, 1]`;
 * exactly one of `Done`/`Cancelled`/`Failed` follows the last `Running` event for a `job_id`
 * (SPEC-010 §2.8's normalize-job convention, generalized here for S4-04's export job).
 */
export type JobState = "running" | "done" | "cancelled" | "failed";

/**
 * Localized display text: English fallback plus an optional i18n key (ADR-005 §2).
 */
export type LocalizedTextDto = { text: string, key: string | null, };

/**
 * S2-03: one marker (SPEC-009 §2.1's essential subset — no `kind`), as `markers_get` reports the
 * list and `marker_add` reports the created marker.
 */
export type MarkerDto = { id: number, pos_samples: number, len_samples: number, name: string, };

/**
 * S2-03: `marker_set_range`'s undo label (SPEC-009 §2.5) — Start keeps `len` (`Move`), End/
 * Duration keep `pos` (`Resize`).
 */
export type MarkerRangeKindDto = "move" | "resize";

/**
 * A module in the registry (`rack_list_modules`; the Add-module menu, grouped client-side by
 * `features`).
 */
export type ModuleDescriptorDto = { id: string, name: LocalizedTextDto, vendor: string, description: LocalizedTextDto, features: Array<string>, };

export type MonitorMode = "off" | "dry" | "through_rack";

/**
 * MP3 encoder settings (mirrors [`vox_io::Mp3Settings`]; ticket S4-02: CBR 128-320 kbps or VBR
 * V0-V4). The ACX preset (PROMPT §3.5) is `Cbr { kbps: 192 }` at 44.1 kHz.
 */
export type Mp3SettingsDto = { "kind": "cbr", kbps: number, } | { "kind": "vbr", quality: number, };

/**
 * A user-facing notice (ADR-003 `notice` event). Two shapes, distinguished by `persistent`:
 * - a **toast** (`persistent: false`, `id: None`): transient, auto-dismisses in the UI (e.g.
 *   SPEC-001 §2.3's fallback/reconnect notices).
 * - a **banner** (`persistent: true`, `id: Some(..)`): stays until the user dismisses it or
 *   another `Notice` with the same `id` replaces/clears it (e.g. SPEC-001 §2.3's device-lost
 *   banner turning into a brief "reconnected" notice).
 *
 * `key`/`params` is an i18n message key plus its placeholder values (CLAUDE.md: every
 * user-facing string goes through i18n) — this event never carries pre-rendered text.
 */
export type Notice = { level: NoticeLevel, key: string, params: { [key in string]: string }, persistent: boolean, 
/**
 * Stable id for a banner that a later `Notice` can replace or clear. `None` for one-shot
 * toasts, which are never replaced (each is its own event).
 */
id: string | null, };

export type NoticeLevel = "info" | "warning" | "error";

/**
 * A parameter changed (`param_changed` event): the slot's current index plus its new value.
 */
export type ParamChangedDto = { slot: number, id: number, value: number, normalized: number, text: string, };

/**
 * Widget-relevant flags (SPEC-012 §2.6 "Widgets from flags"): booleans rather than a raw bit
 * set, so the UI never needs to know the bit layout.
 */
export type ParamFlagsDto = { automatable: boolean, stepped: boolean, boolean: boolean, read_only: boolean, hidden: boolean, bypass: boolean, };

/**
 * A parameter group (SPEC-012 §2.6 layout: a header toggle when `enable_param` is set, one
 * nesting level via `parent`).
 */
export type ParamGroupDto = { id: number, key: string, name: LocalizedTextDto, parent: number | null, enable_param: number | null, collapsed_by_default: boolean, };

/**
 * One parameter's schema (SPEC-012 §2.6). `id`/`group` are the raw ids `param_set_normalized`,
 * `param_set_text` and [`ParamGroupDto::enable_param`] address.
 */
export type ParamInfoDto = { id: number, key: string, name: LocalizedTextDto, group: number | null, unit: UnitDto, min: number, max: number, default: number, taper: TaperDto, step: number | null, enum_labels: Array<LocalizedTextDto>, decimals: number, smoothing_ms: number, flags: ParamFlagsDto, };

/**
 * Current value of one parameter: plain, normalized, and Rust's own display text (SPEC-012
 * §2.6: "displayed text is always Rust's formatting").
 */
export type ParamValueDto = { id: number, value: number, normalized: number, text: string, };

/**
 * `peaks_get`'s request (ADR-003 §2's `PeaksRequest`). `audio_rev` is the revision the UI last
 * saw; the server always answers with the document's *current* `audio_rev` regardless (in its
 * `VXPK` response header) — staleness is the caller's problem to detect (ADR-003: "the UI drops
 * any response whose `audio_rev` is not current"), not something this command refuses.
 */
export type PeaksRequestDto = { request_id: number, audio_rev: number, spp: number, start_sample: number, count: number, };

/**
 * The rack's total latency changed (`rack_latency` event, SPEC-012 §2.5).
 */
export type RackLatencyDto = { latency_samples: number, };

/**
 * One rack slot: identity, status, schema and current values (`rack_get`, every mutating
 * command's result, `rack_changed`).
 */
export type RackSlotDto = { 
/**
 * Stable within this rack's lifetime (never persisted; not the slot's position).
 */
uid: number, 
/**
 * `"id@version"`, or the stored reference verbatim for a placeholder.
 */
module: string, name: string, bypass: boolean, latency_samples: number, status: SlotStatusDto, params: Array<ParamInfoDto>, groups: Array<ParamGroupDto>, 
/**
 * Index-aligned with `params`; empty for a placeholder (no schema).
 */
values: Array<ParamValueDto>, };

/**
 * The rack panel's whole state (`rack_get`, every mutating command's result, and the
 * `rack_changed` event).
 */
export type RackStateDto = { 
/**
 * Slots, top to bottom (processing order).
 */
slots: Array<RackSlotDto>, 
/**
 * Whole-rack A/B state (listening only, SPEC-012 §2.3).
 */
ab: boolean, latency_samples: number, };

/**
 * The record panel state (SPEC-002 §2.1–§2.2, §2.7).
 */
export type RecordStateDto = { 
/**
 * Configured input device (`None`: Arm and Record are unavailable).
 */
input_device: string | null, 
/**
 * Applied 1-based input channel.
 */
input_channel: number, input_status: DeviceStatusDto, 
/**
 * Input armed (never persisted).
 */
armed: boolean, 
/**
 * The input stream is open (meter running).
 */
input_open: boolean, 
/**
 * The open input's rate = the rate of a new recording.
 */
input_rate_hz: number | null, recording: boolean, 
/**
 * Stop was requested; the take is being finished and committed.
 */
finishing: boolean, monitor: MonitorMode, 
/**
 * Monitoring is audible now.
 */
monitoring: boolean, };

/**
 * The whole settings file. `#[serde(default)]` at the container level means any field missing
 * from the on-disk JSON (an older/partial file) is filled from [`Settings::default`], and the
 * flattened `extra` map preserves any *unknown* field a future version wrote, so round-tripping
 * through this version never silently drops it (acceptance criterion: "unknown future fields
 * preserved").
 */
export type Settings = { version: number, device: DevicePrefsDto, default_format: DefaultFormatDto, monitor_mode: MonitorMode, 
/**
 * SPEC-003 §3: {30, 60} Hz, default 60 (measured free on WebKitGTK, ADR-009 §3).
 */
telemetry_rate_hz: number, memory_budget_mib: number, };

/**
 * Slot status (SPEC-012 §2.2, §2.9). `message` is pre-rendered English text shown verbatim (see
 * the module docs) — a plugin or module name isn't something the UI can key into i18n.
 */
export type SlotStatusDto = { "kind": "active" } | { "kind": "missing", message: string, too_new: boolean, } | { "kind": "failed", message: string, };

/**
 * Control mapping ([`Taper`]).
 */
export type TaperDto = { "kind": "linear" } | { "kind": "log" } | { "kind": "db", neg_inf_at_min: boolean, };

/**
 * Transport state (`transport_state` event, transport command results). While playing, the
 * moving playhead comes from `VXTM` telemetry; `playhead_samples` is then where the pass began.
 */
export type TransportStateDto = { playing: boolean, playhead_samples: number, play_start_samples: number, doc_len_samples: number, doc_rate_hz: number, 
/**
 * A document is loaded and an output device is open.
 */
can_play: boolean, };

/**
 * Display unit ([`Unit`]); `Custom` carries the adapter-provided label.
 */
export type UnitDto = { "kind": "none" } | { "kind": "db" } | { "kind": "dbfs" } | { "kind": "dbtp" } | { "kind": "lufs" } | { "kind": "hz" } | { "kind": "ms" } | { "kind": "seconds" } | { "kind": "percent" } | { "kind": "ratio" } | { "kind": "samples" } | { "kind": "custom", label: string, };
