// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `acx_check`'s result: whole-document pass/fail (`passes`, every rule must pass) plus each
 * rule's row.
 */
export type AcxCheckReportDto = { passes: boolean, rms: AcxRuleDto, peak: AcxRuleDto, noise_floor: AcxRuleDto, };

/**
 * `acx_check`'s argument.
 */
export type AcxCheckRequestDto = { source: LoudnessSourceDto, };

/**
 * One rule's row in the ACX Check table: the measured value (`None` only for
 * [`AcxRuleStatusDto::TooShort`]) and its pass/fail status.
 */
export type AcxRuleDto = { measured_db: number | null, status: AcxRuleStatusDto, };

/**
 * Mirrors [`AcxRuleStatus`].
 */
export type AcxRuleStatusDto = "pass" | "too_low" | "too_high" | "invalid" | "too_short";

/**
 * Analyzer averaging response (Fast/Medium/Slow, SPEC-007 §2.9), exponential averaging in the
 * power domain with τ = 50 / 150 / 500 ms.
 */
export type AnalyzerResponseDto = "fast" | "medium" | "slow";

/**
 * The live analyzer's averaging response, persisted (SPEC-007 §2.9: "visibility and response
 * settings are persisted"). Mirrors `vox_engine::analyzer::Response`/`AnalyzerResponseDto` — kept
 * as its own type so `settings` doesn't depend on `ipc`/`vox_engine` (same reasoning as
 * `MonitorMode` above, converted at the IPC boundary).
 */
export type AnalyzerResponsePref = "fast" | "medium" | "slow";

/**
 * Basic app identity shown by the UI at startup. Returned by the `app_info` command.
 */
export type AppInfo = { name: string, version: string, };

export type BitDepth = "16" | "24" | "32f";

/**
 * S2-01: the clipboard's length/rate (`clipboard_changed` event); `null` fields mean it's empty
 * (SPEC-008 §4.3).
 */
export type ClipboardChangedDto = { len_samples: number | null, sample_rate_hz: number | null, };

export type CommandName = "app_info" | "settings_get" | "settings_set" | "devices_list" | "devices_select" | "transport_get" | "transport_play" | "transport_pause" | "transport_stop" | "transport_play_from_start" | "transport_return_to_start" | "transport_seek" | "telemetry_subscribe" | "clock_now_ns" | "rack_list_modules" | "rack_get" | "rack_add" | "rack_remove" | "rack_move" | "rack_bypass" | "rack_ab" | "rack_restart" | "param_set_normalized" | "param_set_text" | "param_set_plain" | "rack_response_curve" | "module_telemetry_subscribe" | "analyzer_subscribe" | "analyzer_set_response" | "analyzer_unsubscribe" | "record_get" | "record_arm" | "record_start" | "record_stop" | "record_set_monitor" | "record_peaks_get" | "document_open" | "document_open_cancel" | "document_probe" | "document_save" | "document_save_as" | "document_close" | "sidecar_view_set_spectral" | "sidecar_view_set_waveform" | "recent_files_get" | "recent_files_remove" | "recent_files_clear" | "recovery_list" | "recovery_recover" | "recovery_discard" | "storage_info" | "peaks_get" | "spectro_attach" | "spectro_detach" | "spectro_request" | "edit_cut" | "edit_copy" | "edit_paste" | "edit_delete" | "edit_trim" | "edit_silence" | "edit_normalize_peak_start" | "edit_normalize_peak_cancel" | "edit_normalize_lufs_start" | "edit_normalize_lufs_cancel" | "history_undo" | "history_redo" | "markers_get" | "marker_add" | "marker_rename" | "marker_set_range" | "marker_delete" | "export_formats" | "export_start" | "export_cancel" | "nr_capture_start" | "nr_capture_cancel" | "loudness_analyze_start" | "loudness_analyze_cancel" | "acx_check";

/**
 * One draggable EQ-graph node (S3-07, SPEC-015 §3 "ResponseCurve components"): the band's
 * frequency/gain/Q/enable parameter ids, and which row of `rack_response_curve`'s
 * `components_db` is its own response. `gain`/`q` are `None` for HP/LP (SPEC-015 §3 "handles").
 */
export type CurveHandleDto = { component: number, freq: number, gain: number | null, q: number | null, enable: number | null, };

export type DefaultFormatDto = { sample_rate_hz: number, bit_depth: BitDepth, };

/**
 * One device of the selected host.
 */
export type DeviceDto = { 
/**
 * Unique name (the key saved in the prefs).
 */
name: string, 
/**
 * Display name.
 */
base_name: string, input: boolean, output: boolean, 
/**
 * Input channels (S1-04 channel dropdown; 0 while unknown).
 */
input_channels: number, 
/**
 * A "follow the system default" pseudo-device.
 */
system_default: boolean, 
/**
 * Its capture side monitors an output (hidden from the input list).
 */
input_is_monitor: boolean, 
/**
 * SPEC-001 §2.1 common rates the output supports (empty while unknown).
 */
output_rates_hz: Array<number>, 
/**
 * SPEC-001 §2.1 common buffer sizes within the output's range ("Auto" is implicit).
 */
output_buffer_sizes: Array<number>, };

/**
 * Persisted device selection — "saved intent", not the applied value: SPEC-001 §2.5 requires
 * that a value which triggered a runtime fallback (unsupported sample rate, out-of-range buffer
 * size) is still saved as the user's *intent*, so PowerVoice retries it next time the device's
 * capabilities might have changed. This DTO therefore never carries a "what was actually
 * applied" field — that belongs to runtime state/telemetry (a later ticket), not settings.
 */
export type DevicePrefsDto = { 
/**
 * Audio host/backend id (SPEC-001 §3: `alsa`|`pipewire`|`jack` on Linux, `wasapi` on
 * Windows, `coreaudio` on macOS). Kept as a plain string rather than a closed enum: only
 * the engine (T-102) can enumerate which hosts actually exist on this machine.
 */
host: string, 
/**
 * `None` = "None" (SPEC-001 §3 factory default; disarms recording/monitoring input).
 * Otherwise the device's host-reported name — devices are keyed by `(host, name)`, not
 * index (SPEC-001 §2.2: cpal indices aren't stable across enumerations).
 */
input_device: string | null, 
/**
 * 1-based input channel index (SPEC-001 §3: `1..=N`, N = device max input channels).
 */
input_channel: number, 
/**
 * `None` = host default output device (SPEC-001 §3).
 */
output_device: string | null, 
/**
 * `None` = device default sample rate ("Auto" is not a documented option for rate in
 * SPEC-001 §3, but no saved preference yet behaves the same as "use the device default").
 */
sample_rate_hz: number | null, 
/**
 * `None` = "Auto" (device default; SPEC-001 §3 factory default).
 */
buffer_size_frames: number | null, };

/**
 * Output status dot (SPEC-001 §2.3).
 */
export type DeviceStatusDto = "not_selected" | "healthy" | "fallback" | "lost";

/**
 * The Audio Devices dialog's data (`devices_list`, `devices_select`, `devices_changed`).
 */
export type DevicesDto = { hosts: Array<string>, host: string | null, devices: Array<DeviceDto>, default_input: string | null, default_output: string | null, 
/**
 * The saved intent.
 */
prefs: DevicePrefsDto, 
/**
 * Applied output device, rate and buffer (`None` = Auto / not open).
 */
output_device: string | null, output_rate_hz: number | null, output_buffer_frames: number | null, output_status: DeviceStatusDto, 
/**
 * The configured input device and its status dot (S1-04).
 */
input_device: string | null, input_status: DeviceStatusDto, };

/**
 * `document_changed` event payload, and the result of `document_open`/`document_save`/
 * `document_save_as`. `name: None` means no document is open.
 */
export type DocumentDto = { name: string | null, path: string | null, sample_rate_hz: number, len_samples: number, dirty: boolean, audio_rev: number, 
/**
 * T-306 (SPEC-018 §2.4): `*` and the close/quit prompts fire on `dirty || sidecar_dirty`.
 */
sidecar_dirty: boolean, 
/**
 * T-306 (SPEC-018 §2.6.5): the sidecar's spectral-pane settings, if any (`null` = keep the
 * UI's current/last-used settings, SPEC-007 §2.1).
 */
spectral_view: SpectralViewDto | null, 
/**
 * H-12 (SPEC-018 §2.6.5): the sidecar's waveform viewport/selection/cursor, if any (`null` =
 * keep the UI's current viewport, e.g. a newly opened document zooms to fit instead).
 */
waveform_view: WaveformViewDto | null, 
/**
 * T-301 (SPEC-004 §2.7): opened by crash recovery and not saved since — the title shows
 * "(recovered)".
 */
recovered: boolean, };

/**
 * T-202: `document_probe`'s result (SPEC-005 §2.3 step 1, §2.4). `channel_peaks_dbfs` is empty
 * for mono (no downmix choice applies); `-inf`/`NaN` peaks serialize as JSON `null`
 * (`serde_json`'s `float_roundtrip` behaviour, same convention as `loudness_dto`).
 */
export type DocumentProbeDto = { container: string, codec: string, sample_rate_hz: number, channels: Array<ProbeChannelDto>, len_samples: number | null, channel_peaks_dbfs: Array<number>, identical_channels: boolean, suggested_channel: number | null, };

/**
 * T-209 (SPEC-005 §2.4): the channel-choice dialog's answer, sent back with a second
 * `document_open` call. `Channel.index` is 0-based, into the source's own channel list (matching
 * [`ProbeChannelDto`]'s order and [`vox_io::DownmixChoice::Channel`]).
 */
export type DownmixChoiceDto = { "kind": "average" } | { "kind": "channel", index: number, };

/**
 * S2-01: the result of a cut/copy/paste/delete/trim/silence command or an undo/redo (SPEC-008
 * §4.3's `EditResult`, minus `rev`/`base_rev` — revision-guarded commands are deferred).
 * `changed: false` only for Copy, a whole-document Trim, and undo/redo at the history's edge.
 */
export type EditResultDto = { changed: boolean, audio_rev: number, len_samples: number, 
/**
 * `[start, end)` document samples, or `null` (no selection).
 */
selection: [number, number] | null, playhead_samples: number, };

/**
 * S2-01: where `edit_paste` inserts or replaces (SPEC-008 §2.1). The UI resolves "no selection"
 * to `Cursor` itself (SPEC-008 §2.2: an empty selection counts as the cursor).
 */
export type EditTargetDto = { "kind": "cursor", at_samples: number, } | { "kind": "range", start_samples: number, end_samples: number, };

export type EventName = "notice" | "transport_state" | "devices_changed" | "rack_changed" | "param_changed" | "rack_latency" | "record_state" | "document_changed" | "history_state" | "clipboard_changed" | "job_progress" | "loudness_report" | "normalize_result" | "recent_files_changed";

/**
 * Export output format and its per-format settings. FLAC's `bits` rejects `"32f"` (FLAC has no
 * float sample format, SPEC-005 §2.11) with `error.export.flac_no_float`.
 */
export type ExportFormatDto = { "kind": "wav", bits: BitDepth, } | { "kind": "flac", bits: BitDepth, } | { "kind": "mp3", settings: Mp3SettingsDto, };

/**
 * `export_formats`' result: whether MP3 is available on this system (ADR-007 §4, D-013). WAV and
 * FLAC are always available.
 */
export type ExportFormatsDto = { mp3_available: boolean, };

/**
 * `[start_sample, end_sample)` of the export (a selection); omitted in the request = whole file.
 */
export type ExportRangeDto = { start_sample: number, end_sample: number, };

/**
 * `export_start`'s argument.
 */
export type ExportRequestDto = { path: string, format: ExportFormatDto, sample_rate_hz: number, range: ExportRangeDto | null, };

/**
 * `export_start`'s result: the export runs in the background, reporting `job_progress` events
 * tagged with this `job_id` (`export_cancel(job_id)` stops it).
 */
export type ExportStartedDto = { job_id: number, };

/**
 * S2-01: the Edit menu's Undo/Redo state (`history_state` event). Labels are i18n keys
 * (`history.cut`, …, CLAUDE.md), `null` when there's nothing to undo/redo.
 */
export type HistoryStateDto = { can_undo: boolean, can_redo: boolean, undo_label: string | null, redo_label: string | null, 
/**
 * T-301 (ADR-004 Amendment 3): placeholder values of `undo_label` (e.g. `target` of
 * "Normalize to {target} dB"); empty when it has none.
 */
undo_label_params: { [key in string]: string }, redo_label_params: { [key in string]: string }, };

/**
 * Error shape returned by every command (ADR-003). `key` is an i18n key, `params` fills its
 * placeholders (CLAUDE.md: every user-facing string goes through i18n — commands never return
 * pre-rendered text).
 */
export type IpcError = { code: IpcErrorCode, key: string, params: { [key in string]: string }, };

/**
 * Coarse error classification shared by every command (ADR-003). This ticket (T-104) fixes the
 * taxonomy shape and fills in the codes already named by an approved spec/ADR; a command-owning
 * ticket adds a new variant here only when its own spec names a distinct error condition, to
 * keep this a small, meaningful set rather than one variant per command.
 */
export type IpcErrorCode = "internal" | "invalid_argument" | "not_found" | "not_while_recording" | "device_not_found" | "device_lost" | "io" | "cancelled" | "busy" | "needs_confirmation";

/**
 * A long-running, cancellable job's kind (ADR-003 `job_progress`; S4-04 is the first job). New
 * job kinds add a variant here rather than a new event, so the frontend has one progress/cancel
 * pattern for every job.
 */
export type JobKind = "export" | "import" | "nr_capture" | "loudness_analyze" | "normalize_peak" | "normalize_lufs";

/**
 * `job_progress` event payload (ADR-003; ≤ 10 Hz per job). `job_id` distinguishes overlapping or
 * stale jobs of the same `kind`; a failure's message goes out separately as a `notice` (the same
 * convention `error.*`/`notice.*` i18n keys use everywhere else), not inline here.
 */
export type JobProgressDto = { job_id: number, kind: JobKind, state: JobState, fraction: number, };

/**
 * `job_progress`'s lifecycle. `Running` fractions are monotonically non-decreasing in `[0, 1]`;
 * exactly one of `Done`/`Cancelled`/`Failed` follows the last `Running` event for a `job_id`
 * (SPEC-010 §2.8's normalize-job convention, generalized here for S4-04's export job).
 */
export type JobState = "running" | "done" | "cancelled" | "failed";

/**
 * Localized display text: English fallback plus an optional i18n key (ADR-005 §2).
 */
export type LocalizedTextDto = { text: string, key: string | null, };

/**
 * `loudness_analyze_start`'s argument: the scope (`None` = whole file) and which signal to
 * measure (ticket: "processed by default, with a source toggle").
 */
export type LoudnessAnalyzeRequestDto = { start_sample: number | null, end_sample: number | null, source: LoudnessSourceDto, };

/**
 * `loudness_analyze_start`'s result: the job runs in the background, reporting `job_progress`
 * (`JobKind::LoudnessAnalyze`) tagged with this `job_id`, then a `loudness_report` event once
 * done (`loudness_analyze_cancel(job_id)` stops it early).
 */
export type LoudnessAnalyzeStartedDto = { job_id: number, };

/**
 * The `loudness_report` event payload: `job_id` ties it to the `job_progress` events of the same
 * job (S4-01 ticket's report shape: I / S-max / M-max / LRA / sample peak / TP).
 */
export type LoudnessReportDto = { job_id: number, integrated_lufs: number, max_momentary_lufs: number | null, max_short_term_lufs: number | null, lra_lu: number, sample_peak_dbfs: number, true_peak_dbtp: number, };

/**
 * Mirrors [`LoudnessSource`].
 */
export type LoudnessSourceDto = "processed" | "source";

/**
 * S2-03: one marker (SPEC-009 §2.1's essential subset — no `kind`), as `markers_get` reports the
 * list and `marker_add` reports the created marker.
 */
export type MarkerDto = { id: number, pos_samples: number, len_samples: number, name: string, };

/**
 * S2-03: `marker_set_range`'s undo label (SPEC-009 §2.5) — Start keeps `len` (`Move`), End/
 * Duration keep `pos` (`Resize`).
 */
export type MarkerRangeKindDto = "move" | "resize";

/**
 * A module in the registry (`rack_list_modules`; the Add-module menu, grouped client-side by
 * `features`).
 */
export type ModuleDescriptorDto = { id: string, name: LocalizedTextDto, vendor: string, description: LocalizedTextDto, features: Array<string>, };

export type MonitorMode = "off" | "dry" | "through_rack";

/**
 * MP3 encoder settings (mirrors [`vox_io::Mp3Settings`]; ticket S4-02: CBR 128-320 kbps or VBR
 * V0-V4). The ACX preset (PROMPT §3.5) is `Cbr { kbps: 192 }` at 44.1 kHz.
 */
export type Mp3SettingsDto = { "kind": "cbr", kbps: number, } | { "kind": "vbr", quality: number, };

/**
 * Settings → Files' remembered policy for opening a multichannel file: "Ask" (default) shows the
 * channel-choice dialog; the other two apply without it. `AlwaysFirstChannel` picks the file's
 * first channel (0-based index 0), not the silent-channel hint's suggestion — that hint only
 * applies to the dialog itself.
 */
export type MultichannelPolicy = "ask" | "always_mix" | "always_first_channel";

/**
 * A slot's noise-print status (S3-06, SPEC-014 §2.5, §2.8). `None` (the outer `Option` this
 * wraps on [`RackSlotDto`]) means the module has no `NoiseProfile` extension — the NR panel
 * section only renders when this DTO is present.
 */
export type NoiseProfileStatusDto = "none" | "loaded" | "unreadable" | "too_new";

/**
 * "The last applied value and unit are remembered in settings across restarts" (SPEC-010 §2.4).
 * `value` is in whichever unit it was last applied in — switching units in the dialog itself
 * converts the *shown* value without touching this until Apply.
 */
export type NormalizeDialogPrefsDto = { value: number, unit: NormalizeTargetUnit, };

/**
 * `edit_normalize_peak_start`/`edit_normalize_lufs_start`'s immediate result: the job id, echoed
 * on every `job_progress`/`normalize_result` event for it (`edit_normalize_peak_cancel`/
 * `edit_normalize_lufs_cancel` stop it).
 */
export type NormalizeJobStartedDto = { job_id: number, };

/**
 * `normalize_result` event payload: the finished job's edit result (SPEC-010 §2.1's selection/
 * `audio_rev`, unchanged for a no-op). Emitted only once the job's `job_progress` reports `Done`
 * — a `Cancelled`/`Failed` job never touched the document, so there is nothing to report here
 * (its failure reason, if any, arrives as a `notice`).
 */
export type NormalizeResultDto = { job_id: number, kind: JobKind, result: EditResultDto, };

/**
 * The Normalize… dialog's unit toggle (SPEC-010 §2.4).
 */
export type NormalizeTargetUnit = "db" | "pct";

/**
 * A user-facing notice (ADR-003 `notice` event). Two shapes, distinguished by `persistent`:
 * - a **toast** (`persistent: false`, `id: None`): transient, auto-dismisses in the UI (e.g.
 *   SPEC-001 §2.3's fallback/reconnect notices).
 * - a **banner** (`persistent: true`, `id: Some(..)`): stays until the user dismisses it or
 *   another `Notice` with the same `id` replaces/clears it (e.g. SPEC-001 §2.3's device-lost
 *   banner turning into a brief "reconnected" notice).
 *
 * `key`/`params` is an i18n message key plus its placeholder values (CLAUDE.md: every
 * user-facing string goes through i18n) — this event never carries pre-rendered text.
 */
export type Notice = { level: NoticeLevel, key: string, params: { [key in string]: string }, persistent: boolean, 
/**
 * Stable id for a banner that a later `Notice` can replace or clear. `None` for one-shot
 * toasts, which are never replaced (each is its own event).
 */
id: string | null, };

export type NoticeLevel = "info" | "warning" | "error";

/**
 * `nr_capture_start`'s immediate result: the job id (echoed on every `job_progress` event for
 * it) and the resolved target slot index — authoritative even when a slot was just inserted, so
 * the panel can show the spinner on the right one without waiting for `rack_changed`.
 */
export type NrCaptureStartedDto = { job_id: number, slot: number, };

/**
 * A parameter changed (`param_changed` event): the slot's current index plus its new value.
 */
export type ParamChangedDto = { slot: number, id: number, value: number, normalized: number, text: string, };

/**
 * Widget-relevant flags (SPEC-012 §2.6 "Widgets from flags"): booleans rather than a raw bit
 * set, so the UI never needs to know the bit layout.
 */
export type ParamFlagsDto = { automatable: boolean, stepped: boolean, boolean: boolean, read_only: boolean, hidden: boolean, bypass: boolean, };

/**
 * A parameter group (SPEC-012 §2.6 layout: a header toggle when `enable_param` is set, one
 * nesting level via `parent`).
 */
export type ParamGroupDto = { id: number, key: string, name: LocalizedTextDto, parent: number | null, enable_param: number | null, collapsed_by_default: boolean, };

/**
 * One parameter's schema (SPEC-012 §2.6). `id`/`group` are the raw ids `param_set_normalized`,
 * `param_set_text` and [`ParamGroupDto::enable_param`] address.
 */
export type ParamInfoDto = { id: number, key: string, name: LocalizedTextDto, group: number | null, unit: UnitDto, min: number, max: number, default: number, taper: TaperDto, step: number | null, enum_labels: Array<LocalizedTextDto>, decimals: number, smoothing_ms: number, flags: ParamFlagsDto, };

/**
 * Current value of one parameter: plain, normalized, and Rust's own display text (SPEC-012
 * §2.6: "displayed text is always Rust's formatting").
 */
export type ParamValueDto = { id: number, value: number, normalized: number, text: string, };

/**
 * `peaks_get`'s request (ADR-003 §2's `PeaksRequest`). `audio_rev` is the revision the UI last
 * saw; the server always answers with the document's *current* `audio_rev` regardless (in its
 * `VXPK` response header) — staleness is the caller's problem to detect (ADR-003: "the UI drops
 * any response whose `audio_rev` is not current"), not something this command refuses.
 */
export type PeaksRequestDto = { request_id: number, audio_rev: number, spp: number, start_sample: number, count: number, };

/**
 * T-202: one source channel's role (SPEC-005 §2.4), part of `document_probe`'s payload — the
 * data a future channel-choice dialog (T-209) needs.
 */
export type ProbeChannelDto = { label: string, is_lfe: boolean, };

/**
 * The rack's total latency changed (`rack_latency` event, SPEC-012 §2.5).
 */
export type RackLatencyDto = { latency_samples: number, };

/**
 * One rack slot: identity, status, schema and current values (`rack_get`, every mutating
 * command's result, `rack_changed`).
 */
export type RackSlotDto = { 
/**
 * Stable within this rack's lifetime (never persisted; not the slot's position).
 */
uid: number, 
/**
 * `"id@version"`, or the stored reference verbatim for a placeholder.
 */
module: string, name: string, bypass: boolean, latency_samples: number, status: SlotStatusDto, params: Array<ParamInfoDto>, groups: Array<ParamGroupDto>, 
/**
 * Index-aligned with `params`; empty for a placeholder (no schema).
 */
values: Array<ParamValueDto>, 
/**
 * `Some` only for a module with the `NoiseProfile` extension (S3-06): drives the NR panel's
 * Capture button and status line.
 */
noise_profile: NoiseProfileStatusDto | null, 
/**
 * `Some` only for a module with the `ResponseCurve` extension (S3-07): the EQ graph panel
 * only renders when this is present, generic to any future module that exposes a curve.
 */
curve_handles: Array<CurveHandleDto> | null, 
/**
 * The module's telemetry channels (H-03): empty without the `Telemetry` extension (and for
 * placeholders). The slot header shows the `gain_reduction` channels whose `group` is `null`
 * as meters, fed by `VXMT` frames.
 */
telemetry: Array<TelemetryChannelDto>, };

/**
 * The rack panel's whole state (`rack_get`, every mutating command's result, and the
 * `rack_changed` event).
 */
export type RackStateDto = { 
/**
 * Slots, top to bottom (processing order).
 */
slots: Array<RackSlotDto>, 
/**
 * Whole-rack A/B state (listening only, SPEC-012 §2.3).
 */
ab: boolean, latency_samples: number, };

/**
 * One `File → Open Recent` entry. `name`/`folder` are split out so the menu can show
 * "‹name› — ‹folder›" without re-deriving them in the UI; `exists` is resolved within the
 * existence-check budget (SPEC-018 §2.12) — `null` only if the check couldn't complete in time
 * (a stalled network mount), in which case the entry is shown as if it existed.
 */
export type RecentFileDto = { path: string, name: string, folder: string, exists: boolean | null, };

/**
 * One `recent_files` entry. `path` is the path as opened/saved (informational — dedup and
 * matching compare canonicalized paths, `vox_project::canonical_path_for_compare`); `opened_at`
 * is RFC 3339 UTC.
 */
export type RecentFileEntry = { path: string, opened_at: string, };

/**
 * The record panel state (SPEC-002 §2.1–§2.2, §2.7).
 */
export type RecordStateDto = { 
/**
 * Configured input device (`None`: Arm and Record are unavailable).
 */
input_device: string | null, 
/**
 * Applied 1-based input channel.
 */
input_channel: number, input_status: DeviceStatusDto, 
/**
 * Input armed (never persisted).
 */
armed: boolean, 
/**
 * The input stream is open (meter running).
 */
input_open: boolean, 
/**
 * The open input's rate = the rate of a new recording.
 */
input_rate_hz: number | null, recording: boolean, 
/**
 * Stop was requested; the take is being finished and committed.
 */
finishing: boolean, monitor: MonitorMode, 
/**
 * Monitoring is audible now.
 */
monitoring: boolean, 
/**
 * T-107 (SPEC-002 §2.7, §4.4): the monitoring latency readout in µs (0.1 ms steps) — input
 * latency + monitor buffer + rack latency (through-rack only) + output latency; `None` while
 * the mode is Off or a stream is closed. Amber ≥ 20 ms, red ≥ 40 ms (UI).
 */
monitor_latency_us: number | null, 
/**
 * T-107: monitor dropouts (underruns faded out/in, overruns dropped back) since the output
 * opened. The take is unaffected.
 */
monitor_dropouts: number, 
/**
 * H-10 item 4: dropout events so far this take (SPEC-002 §2.1's live amber counter), `0`
 * while not recording.
 */
dropout_count: number, 
/**
 * H-11 (SPEC-002 §2.5, AC-13): remaining recording time on the session volume, in whole
 * seconds; `None` when the free-space query failed.
 */
disk_remaining_s: number | null, };

/**
 * `recovery_recover`'s result: the recovered document (modified, `recovered: true`) and how
 * many changes were lost (the "could not be recovered" notice also goes out as an event).
 */
export type RecoverResultDto = { document: DocumentDto, lost_changes: number, };

/**
 * One recoverable session, as the start-up dialog and Settings → Recovery & storage list it
 * (SPEC-004 §2.7): `name`/`path` are `null` for an untitled recording ("Untitled recording").
 */
export type RecoverableSessionDto = { id: string, name: string | null, path: string | null, 
/**
 * The last edit time (the journal's mtime), ms since the Unix epoch.
 */
last_modified_unix_ms: number | null, 
/**
 * "3 unsaved changes".
 */
unsaved_changes: number, 
/**
 * A recording was in progress: its recovered length in samples.
 */
recording_samples: number | null, sample_rate_hz: number, 
/**
 * "‹name› changed on disk since you opened it…".
 */
source_changed: boolean, 
/**
 * The bound file no longer exists (recovery still works; Save recreates it).
 */
source_missing: boolean, 
/**
 * The journal has a damaged tail: some of the latest changes may be lost.
 */
damaged: boolean, size_bytes: number, };

/**
 * What Recover does with an interrupted take (SPEC-004 §2.7; "apply" is the default).
 */
export type RecoveredTakeActionDto = "apply" | "new_document" | "discard";

/**
 * `rack_response_curve`'s response (S3-07, SPEC-015 §2.6.6, lean slice: JSON — the binary
 * `VXRC` frame is hardening). `components_db` is one row per band, in `curve_handles` order.
 */
export type ResponseCurveDto = { freqs_hz: Array<number>, sample_rate_hz: number, total_db: Array<number>, components_db: Array<Array<number>>, };

/**
 * T-209 (SPEC-005 §2.6/§2.7): the Save As dialog's format row — WAV (16/24-bit int or 32-bit
 * float, via the existing `BitDepth`) or FLAC (16/24-bit only; `Bit32Float` with `Flac` is
 * refused, `error.save.flac_needs_int_bits`).
 */
export type SaveContainerDto = "wav" | "flac";

/**
 * The whole settings file. `#[serde(default)]` at the container level means any field missing
 * from the on-disk JSON (an older/partial file) is filled from [`Settings::default`], and the
 * flattened `extra` map preserves any *unknown* field a future version wrote, so round-tripping
 * through this version never silently drops it (acceptance criterion: "unknown future fields
 * preserved").
 */
export type Settings = { version: number, device: DevicePrefsDto, default_format: DefaultFormatDto, monitor_mode: MonitorMode, 
/**
 * T-107 (SPEC-002 §2.7): the one-time "use headphones" hint was shown (it appears the first
 * time monitoring is enabled).
 */
monitor_hint_shown: boolean, 
/**
 * SPEC-003 §3: {30, 60} Hz, default 60 (measured free on WebKitGTK, ADR-009 §3).
 */
telemetry_rate_hz: number, memory_budget_mib: number, 
/**
 * H-09/SPEC-010 §2.4: the Normalize… dialog's last applied value and unit.
 */
normalize_dialog: NormalizeDialogPrefsDto, 
/**
 * T-306 (SPEC-018 §2.12): File → Open Recent, most-recent-first, capped at
 * [`RECENT_FILES_MAX`]. Additive field — the settings version stays 1.
 */
recent_files: Array<RecentFileEntry>, 
/**
 * H-12 (A-014): app-wide spectral display defaults, for documents with no sidecar view.
 * Additive field — the settings version stays 1.
 */
spectral_defaults: SpectralDefaultsDto, 
/**
 * H-16 (SPEC-007 §2.9): the live analyzer panel's visibility (shown by default; View →
 * Analyzer toggles it). Additive field — the settings version stays 1.
 */
analyzer_visible: boolean, 
/**
 * H-16 (SPEC-007 §2.9): the analyzer's averaging response (Fast/Medium/Slow). Additive
 * field — the settings version stays 1.
 */
analyzer_response: AnalyzerResponsePref, 
/**
 * H-16 (SPEC-007 §2.9): the analyzer's peak-hold toggle (on by default). Additive field —
 * the settings version stays 1.
 */
analyzer_peak_hold: boolean, 
/**
 * T-209 (SPEC-005 §2.4, §3 `multichannel_policy`): Settings → Files. Additive field — the
 * settings version stays 1.
 */
multichannel_policy: MultichannelPolicy, };

/**
 * Slot status (SPEC-012 §2.2, §2.9). `message` is pre-rendered English text shown verbatim (see
 * the module docs) — a plugin or module name isn't something the UI can key into i18n.
 */
export type SlotStatusDto = { "kind": "active" } | { "kind": "missing", message: string, too_new: boolean, } | { "kind": "failed", message: string, };

/**
 * App-wide default spectral **display** settings (colormap, frequency scale, floor/ceiling, FFT
 * size) — used for a document with no sidecar `view.spectral` section (T-306 already persists
 * those per document, `sidecar_view_set_spectral`; this is only the fallback/seed). Pane
 * visibility and the waveform/spectral split ratio are *not* here: SPEC-018 §2.6.5 keeps those
 * per document only, with no app-wide default (a document without a sidecar just starts with
 * the pane hidden, SPEC-007 §2.1's factory default). Changing a spectral setting in the UI
 * updates both the open document's sidecar view and this default (so the next document without
 * its own sidecar view starts from the last-used look).
 */
export type SpectralDefaultsDto = { freq_scale: string, colormap: string, display_floor_db: number, display_ceil_db: number, 
/**
 * `None` = Auto (SPEC-007 §2.6).
 */
fft_size: number | null, };

/**
 * T-306 (SPEC-018 §2.6.5's `view.spectral`, SPEC-007 §3): per-document spectral pane settings.
 * `fft_size: null` means Auto (SPEC-007 §2.6).
 */
export type SpectralViewDto = { visible: boolean, split_ratio: number, fft_size: number | null, freq_scale: string, display_floor_db: number, display_ceil_db: number, colormap: string, };

/**
 * One `spectro_request`: FFT size, hop (from the zoom, SPEC-007 §4.3), window (0 = Hann) and up
 * to 64 tile indices, visible tiles first.
 */
export type SpectroRequestDto = { request_id: number, audio_rev: number, fft_size: number, hop: number, window: number, tiles: Array<number>, };

/**
 * Settings → Recovery & storage (SPEC-004 §2.5, §2.8): the open document's session storage
 * ("Session storage: 3.2 GB (history 2.1 GB)") and the recoverable sessions with their sizes.
 */
export type StorageInfoDto = { 
/**
 * `null` with no document open.
 */
session_bytes: number | null, history_bytes: number | null, sessions: Array<RecoverableSessionDto>, 
/**
 * Sum of the recoverable sessions' sizes ("Recovery data (X GB)").
 */
recovery_bytes: number, };

/**
 * Control mapping ([`Taper`]).
 */
export type TaperDto = { "kind": "linear" } | { "kind": "log" } | { "kind": "db", neg_inf_at_min: boolean, };

/**
 * One module telemetry channel (H-03, SPEC-016 §4.12 "channel descriptions travel once, with
 * the rack state"). Its values arrive in binary `VXMT` frames (`module_telemetry_subscribe`),
 * keyed by the slot's `uid`, in [`RackSlotDto::telemetry`] order.
 */
export type TelemetryChannelDto = { id: number, key: string, name: LocalizedTextDto, unit: UnitDto, 
/**
 * Display range.
 */
min: number, max: number, kind: TelemetryKindDto, 
/**
 * Group whose header shows the meter; `null` = the slot header.
 */
group: number | null, };

/**
 * What a module telemetry channel's value means ([`TelemetryKind`], ADR-005 §11).
 */
export type TelemetryKindDto = "gain_reduction" | "level" | "indicator" | "value";

/**
 * Transport state (`transport_state` event, transport command results). While playing, the
 * moving playhead comes from `VXTM` telemetry; `playhead_samples` is then where the pass began.
 */
export type TransportStateDto = { playing: boolean, playhead_samples: number, play_start_samples: number, doc_len_samples: number, doc_rate_hz: number, 
/**
 * A document is loaded and an output device is open.
 */
can_play: boolean, };

/**
 * Display unit ([`Unit`]); `Custom` carries the adapter-provided label.
 */
export type UnitDto = { "kind": "none" } | { "kind": "db" } | { "kind": "dbfs" } | { "kind": "dbtp" } | { "kind": "lufs" } | { "kind": "hz" } | { "kind": "ms" } | { "kind": "seconds" } | { "kind": "percent" } | { "kind": "ratio" } | { "kind": "samples" } | { "kind": "custom", label: string, };

/**
 * `[start_sample, end_sample)` document samples (SPEC-006 §2.2's selection shape).
 */
export type WaveformSelectionDto = { start_sample: number, end_sample: number, };

/**
 * H-12 (SPEC-018 §2.6.5's `view.waveform`, this ticket's subset — see `WaveformViewInfo`'s doc
 * for what's deferred): the shared waveform/spectral viewport plus the selection and edit
 * cursor, persisted like `SpectralViewDto`.
 */
export type WaveformViewDto = { start_sample: number, samples_per_pixel: number, 
/**
 * `null` = no selection.
 */
selection: WaveformSelectionDto | null, cursor_samples: number, };
