// Generated by the `export_bindings_vxis_fixture` test (src-tauri, `just gen-types`). Do not edit.

/** A `VXIS` frame encoded by Rust (`InspectorFrame::encode`) for the TS decoder contract test. */
export const VXIS_FIXTURE_HEX =
  "5658495301002800070000000100000080bb000000040000020000000400000002000000000000000000c8c20000d0c000000000000080ff";

/** The field values encoded in `VXIS_FIXTURE_HEX`. */
export const VXIS_FIXTURE_FIELDS = {
  seq: 7,
  reset: true,
  silent: false,
  sampleRateHz: 48000,
  fftSize: 1024,
  window: "flat_top",
  response: "slow",
  levelsDb: [-100, -6.5, 0, -Infinity],
} as const;
