// Generated by the `export_bindings_vxlt_fixture` test (src-tauri, `just gen-types`). Do not edit.

/** A `VXLT` curve frame encoded by Rust (`spectrum::encode_curve`) for the TS decoder contract test. */
export const VXLT_FIXTURE_HEX =
  "56584c5401002400050000000100000044ac00000400000000000000030000000100000000000000c1a8c0c0000080ff000070c20000a0c2000080ff";
