// Generated by the `export_bindings_vxmt_fixture` test (src-tauri, `just gen-types`). Do not edit.

/** A `VXMT` frame encoded by Rust (`ModuleTelemetryFrame::encode`) for the TS decoder contract test. */
export const VXMT_FIXTURE_HEX =
  "56584d5401002000050000000000000068f3c8f4e5000000020000000000000003000000010000000000d0c00c00000003000000000000000000c0c10000803f";

/** The values encoded in `VXMT_FIXTURE_HEX`. */
export const VXMT_FIXTURE_FIELDS = {
  seq: 5,
  frameTimeNs: 987654321000,
  records: [
    { slotUid: 3, values: [-6.5] },
    { slotUid: 12, values: [0, -24, 1] },
  ],
} as const;
