// Generated by the `export_bindings_vxpk_fixture` test (src-tauri, `just gen-types`). Do not edit.

/**
 * `VXPK` frames encoded by Rust (`vox_project::encode_vxpk`) for the TS decoder contract test.
 * Both frames carry the same 4 buckets: bucket `i` is `(-(1 + i / 8), 1 + i / 8)`; the `RAW`
 * frame keeps only each pair's first value.
 */
export const VXPK_FIXTURES = [
  {
    hex: "5658504b0100300009000000020000002a000000000000000000000001000000000400000400000080bb000000000000000080bf0000803f000090bf0000903f0000a0bf0000a03f0000b0bf0000b03f",
    fields: {
      requestId: 9,
      raw: false,
      partial: true,
      audioRev: 42,
      startSample: 4294967296,
      samplesPerBucket: 1024,
      count: 4,
      sampleRateHz: 48000,
    },
  },
  {
    hex: "5658504b010030000a000000010000002a000000000000000000000000000000010000000400000044ac000000000000000080bf000090bf0000a0bf0000b0bf",
    fields: {
      requestId: 10,
      raw: true,
      partial: false,
      audioRev: 42,
      startSample: 0,
      samplesPerBucket: 1,
      count: 4,
      sampleRateHz: 44100,
    },
  },
] as const;
