// Generated by the `export_bindings_vxsa_fixture` test (src-tauri, `just gen-types`). Do not edit.

/** A `VXSA` frame encoded by Rust (`AnalyzerFrame::encode`) for the TS decoder contract test. */
export const VXSA_FIXTURE_HEX =
  "56585341010030000b00000001000000b806b1598100000080bb0000002000000000a0411800000004000000010000000000f0c20000a3c100000000000080ff";

/** The field values encoded in `VXSA_FIXTURE_HEX`. */
export const VXSA_FIXTURE_FIELDS = {
  seq: 11,
  reset: true,
  dropped: false,
  silent: false,
  frameTimeNs: 555555555000,
  sampleRateHz: 48000,
  fftSize: 8192,
  f0Hz: 20,
  bandsPerOctave: 24,
  bandCount: 4,
  response: 1,
  levelsDb: [-120, -20.375, 0, -Infinity],
} as const;
