// Generated by the `export_bindings_vxst_fixture` test (src-tauri, `just gen-types`). Do not edit.

/**
 * `VXST` frames encoded by Rust (`vox_engine::spectro::encode_vxst`) for the TS decoder contract
 * test. Payload code `i` is `(i * 37 + 11) % 256`.
 */
export const VXST_FIXTURES = [
  {
    hex: "565853540100400007000000020000002a00000000000000000060000000000000200000000100000200000081000000000016c30000c04003000000000000000b30557a9fc4e90e33587da2c7ec11365b80a5caef14395e83a8cdf2173c6186abd0f51a3f6489aed3f81d42678cb1d6fb20456a8fb4d9fe23486d92b7dc01264b7095badf04294e7398bde2072c51769bc0e50a2f54799ec3e80d32577ca1c6eb10355a7fa4c9ee13385d82a7ccf1163b6085aacff4193e6388add2f71c41668bb0d5fa1f44698eb3d8fd22476c91b6db00254a6f94b9de03284d7297bce1062b50759abfe4092e53789dc2e70c31567ba0c5ea0f34597ea3c8ed12375c81a6cbf0153a5f84a9cef3183d6287acd1f61b40658aafd4f91e43688db2d7fc21466b90b5daff24496e93b8dd02274c7196bbe0052a4f7499bee3082d52779cc1e60b30",
    fields: {
      requestId: 7,
      flags: 2,
      last: false,
      preview: true,
      audioRev: 42,
      firstFrameCenterSample: 6291456,
      hopSamples: 8192,
      fftSize: 256,
      frames: 2,
      bins: 129,
      qFloorDb: -150,
      qCeilDb: 6,
      tileIndex: 3,
      window: 0,
    },
  },
  {
    hex: "565853540100400007000000010000002a00000000000000000080000000000000200000000100000100000081000000000016c30000c04004000000000000000b30557a9fc4e90e33587da2c7ec11365b80a5caef14395e83a8cdf2173c6186abd0f51a3f6489aed3f81d42678cb1d6fb20456a8fb4d9fe23486d92b7dc01264b7095badf04294e7398bde2072c51769bc0e50a2f54799ec3e80d32577ca1c6eb10355a7fa4c9ee13385d82a7ccf1163b6085aacff4193e6388add2f71c41668b",
    fields: {
      requestId: 7,
      flags: 1,
      last: true,
      preview: false,
      audioRev: 42,
      firstFrameCenterSample: 8388608,
      hopSamples: 8192,
      fftSize: 256,
      frames: 1,
      bins: 129,
      qFloorDb: -150,
      qCeilDb: 6,
      tileIndex: 4,
      window: 0,
    },
  },
] as const;
