// Generated by the `export_bindings_vxtc_fixture` test (src-tauri, `just gen-types`). Do not edit.

/** A `VXTC` frame encoded by Rust (`TransferCurvePoints::encode`) with no Falling branch. */
export const VXTC_FIXTURE_HEX =
  "565854430100280007000000000000000000a0c200000000030000000100000001000000000000000000a0c2000020c20000d0c000000000000000000000d0c01f000000000084c10000604001000000";

/** The values encoded in `VXTC_FIXTURE_HEX`. */
export const VXTC_FIXTURE_FIELDS = {
  seq: 7,
  xMinDb: -80,
  xMaxDb: 0,
  rising: [-80, -40, -6.5],
  falling: null,
  components: [[0, 0, -6.5]],
  handles: [{ param: 31, xDbfs: -16.5, offsetDb: 3.5, enabled: true }],
} as const;

/** The same frame with the `HAS_FALLING` bit, a hysteresis loop and muted (−∞) levels. */
export const VXTC_FALLING_FIXTURE_HEX =
  "565854430100280008000000010000000000a0c20000000003000000020000000200000000000000000080ff000020c20000d0c0000080ff000080ff0000d0c0000080ff000000000000000000000000000000000000d0c00b000000000048c200000000010000001f000000000084c10000604000000000";

/** The values encoded in `VXTC_FALLING_FIXTURE_HEX`. */
export const VXTC_FALLING_FIXTURE_FIELDS = {
  seq: 8,
  xMinDb: -80,
  xMaxDb: 0,
  rising: [-Infinity, -40, -6.5],
  falling: [-Infinity, -Infinity, -6.5],
  components: [[-Infinity, 0, 0], [0, 0, -6.5]],
  handles: [
    { param: 11, xDbfs: -50, offsetDb: 0, enabled: true },
    { param: 31, xDbfs: -16.5, offsetDb: 3.5, enabled: false },
  ],
} as const;
