// Generated by the `export_bindings_vxtm_fixture` test (src-tauri, `just gen-types`). Do not edit.

/** A `VXTM` frame encoded by Rust (`TelemetryFrame::encode`) for the TS decoder contract test. */
export const VXTM_FIXTURE_HEX =
  "5658544d01004800070000001100000015cd5b070000000068f3c8f4e5000000000000008088e5400000d0c00000a2c1000080ff000080ff2a000000000000000300000000000000";

/** The field values encoded in `VXTM_FIXTURE_HEX`. */
export const VXTM_FIXTURE_FIELDS = {
  seq: 7,
  flags: 17,
  playheadSample: 123456789,
  playheadTimeNs: 987654321000,
  rate: 44100,
  outPeakDbfs: -6.5,
  outRmsDbfs: -20.25,
  inPeakDbfs: -Infinity,
  inRmsDbfs: -Infinity,
  audioRev: 42,
  droppedRtEvents: 3,
} as const;
